export default {
  ANDROID: 'android',
  IOS: 'ios',
  APP_ID: '06b6c41aaad74e66ae944240858be524',
  CHANNEL_NAME: 'testingComments',
  GAME_NAME: 'India VS England',
  APP_TYPE: 'Commentary',
  BACKEND_BASEURL: 'http://13.232.207.207:3331',
  MONTH_NAMES: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
};
